# Generated by Django 4.0.5 on 2022-07-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_album_artist_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
    ]
