# Generated by Django 4.0.5 on 2022-07-03 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_favorite_alter_album_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albums.favorite'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
